version: '3'

services: 
    web:
        build: ./backend
        command: gunicorn tender.wsgi:application --bind 0.0.0.0:8000
        ports:
            - "8000:8000" #HOST:CONTAINER
        depends_on: 
            - db
        volumes:
            - ./backend:/app

    db:
        image: postgres
        environment: 
            - POSTGRES_DB=10DerMeatzPostGres
            - POSTGRES_USER=10DerMeatz
            - POSTGRES_PASSWORD=gogetadragon
        ports:
            - "1234:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data

    nginx:
        build: ./nginx
        ports:
            - 8080:8080
        command: nginx -g 'daemon off';
        volumes:
            - ./backend/static-root:/var/www/static
            - ./backend/media-root:/var/www/media
        depends_on: 
            - web
