# Generated by Django 3.0.8 on 2020-07-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('sub_title', models.CharField(default=None, max_length=20)),
                ('Small_description', models.CharField(max_length=200)),
                ('large_description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=1, max_digits=4)),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(default='ADD SOON', max_length=15)),
            ],
        ),
    ]
