# Generated by Django 3.0.8 on 2020-07-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('chicken', 'CHICKEN'), ('mutton', 'MUTTON'), ('seafood', 'SEAFOOD')], default='ADD SOON', max_length=15),
        ),
    ]
