# Generated by Django 3.0.8 on 2020-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200728_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sub_title',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
