# Generated by Django 3.1 on 2020-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200812_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.FloatField(default=500),
        ),
    ]
