# Generated by Django 3.1 on 2020-08-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_delivery_personelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_Personelle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.delivery_personelle'),
        ),
    ]
