# Generated by Django 3.1 on 2020-08-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_order_delivery_personelle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delivery_personelle',
            new_name='deliveryPersonelle',
        ),
    ]
