# Generated by Django 3.1 on 2020-08-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200814_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.deliveryaddress'),
        ),
    ]
