# Generated by Django 3.1 on 2020-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_order_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='lat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='lng',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
