# Generated by Django 3.1 on 2020-08-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
