# Generated by Django 3.1 on 2020-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200815_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
