# Generated by Django 3.1 on 2020-08-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_otp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaoruselImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaoruselImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
