# Generated by Django 3.1 on 2020-08-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_caoruselimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
