# Generated by Django 3.1 on 2020-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20200829_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimages',
            name='categoryInfo',
            field=models.CharField(default='ADDING DESCRIPTION SOON', max_length=200),
        ),
    ]
